version: '3.8'

services:
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: test #rootパスワード。今回はrootにしました。
      MYSQL_DATABASE: test
    ports:
      - '3308:3306' #接続するポート番号。お好きな番号でいけます。
    volumes:
      - my_volume:/var/lib/mysql
    command: mysqld --innodb_use_native_aio=0

volumes:
  my_volume:
