version: '3.8'

services:
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: test #rootパスワード
      MYSQL_DATABASE: test
    ports:
      - '3308:3306'
    volumes:
      - mysql_volume:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d

volumes:
  mysql_volume:
